version: '3.9'

services:
  node:
    build:
      context: .
      target: production
      dockerfile: ./docker/image/production/node/Dockerfile
    networks:
      - mysql
    env_file:
      - production.env
    ports:
      - 3000:3000
    restart: unless-stopped
  mysql:
    image: mariadb:10.7.1
    networks:
      - mysql
    env_file:
      - production.env
    ports:
      - 3306:3306
networks:
  mysql:
